#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#      Filename:  project_euler_002.py
#
#   Description:  Project Euler, Problem 002
#
#       Created:  Sun 12 Jun 2011 04:17:53 AM ICT
# Last Modified:  Sun 12 Jun 2011 05:03:40 AM ICT
#
#        Author:  Thuan.D.T (MrTux)
#       Company:  Water Resources University (WRU)
#     Copyright:  (c) 2011, MrTux <mrtux@ubuntu-vn.org>

"""ProjectEuler, Problem 002

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed
four million.
"""

import time

__author__ = "Thuan.D.T (MrTux)"
__copyright__ = "Copyright (c) 2011 Thuan.D.T (MrTux)"
__credits__ = ["Thuan.D.T"]
__license__ = "GPLv2"
__version__ = "1.0.0"
__maintainer__ = "MrTux"
__email__ = "mrtux@ubuntu-vn.org"
__status__ = "Release"
__company__ = "Water Resources University (WRU)"


def main(): # main
    start = time.time()

    result, a, b = 0, 1, 2
    while b<4000000:
        if b%2 ==0:
            result+=b
        a, b = b, a+b

    # Print Answer and Time Execute
    print "Answer : ", result
    print "Time   : ", str(time.time() - start)
    return 0

if __name__ == '__main__':
    print __doc__
    main()

"""Analysis Problem

F(n) = F(n-1) + F(n-2)
     = 4*F(n-3) + 6*F(n-6)

Bất cứ một hạng tử nào của dãy Fibonaci đều được viết dưới dạng tổng của 2 số
liền sau nó !!!

"""
